os: osx
osx_image: xcode10.3
language: swift
script: xcodebuild clean build test -project TrafficLightCamera/TrafficLightCamera.xcodeproj -scheme "DomainFramework" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES

script: xcodebuild clean build test -project TrafficLightCamera/TrafficLightCamera.xcodeproj -scheme "TrafficLightCamera" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.2.2" ONLY_ACTIVE_ARCH=YES
