os: osx
osx_image: xcode11.6
language: swift
script:
- xcodebuild clean build test -project TrafficLightCamera/TrafficLightCamera.xcodeproj -scheme "DomainFramework" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
- xcodebuild clean build test -project TrafficLightCamera/TrafficLightCamera.xcodeproj -scheme "TrafficLightCamera" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.6,name=iPhone 11" ONLY_ACTIVE_ARCH=YES
