os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -project TrafficLightCamera/TrafficLightCamera.xcodeproj -scheme "DomainFramework" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
